#include "ieth.h"

/*
==============================
 Ieth medias register
==============================
*/

void initCustomSounds() {
	eth.customSounds[CSND_BROWNING_FIRE] = (soundReplace_t) {"sound/weapons/browning/browning_fire.wav",-1, -1};
	eth.customSounds[CSND_COLT_FAR] = (soundReplace_t) {"sound/weapons/colt/colt_far.wav",-1, -1};
	eth.customSounds[CSND_COLT_FIRE] = (soundReplace_t) {"sound/weapons/colt/colt_fire.wav",-1, -1};
	eth.customSounds[CSND_COLT_RELOAD] = (soundReplace_t) {"sound/weapons/colt/colt_reload.wav",-1, -1};
	eth.customSounds[CSND_COLT_SILENCE] = (soundReplace_t) {"sound/weapons/colt/colt_silence.wav",-1, -1};
	eth.customSounds[CSND_FG42_FIRE] = (soundReplace_t) {"sound/weapons/fg42/fg42_fire.wav",-1, -1};
	eth.customSounds[CSND_M1_FIREGRN] = (soundReplace_t) {"sound/weapons/garand/m1_fire_grenade.wav",-1, -1};
	eth.customSounds[CSND_M1_FIRE] = (soundReplace_t) {"sound/weapons/garand/m1_fire.wav",-1, -1};
	eth.customSounds[CSND_K43_FIRE] = (soundReplace_t) {"sound/weapons/k43/k43_fire.wav",-1, -1};
	eth.customSounds[CSND_MINE_STEP] = (soundReplace_t) {"sound/weapons/landmine/mine_on.wav",-1, -1};
	eth.customSounds[CSND_LUGER_FIRE] = (soundReplace_t) {"sound/weapons/luger/luger_fire.wav",-1, -1};
	eth.customSounds[CSND_LUGER_FAR] = (soundReplace_t) {"sound/weapons/luger/luger_far.wav",-1, -1};
	eth.customSounds[CSND_LUGER_SLND] = (soundReplace_t) {"sound/weapons/luger/luger_silence.wav",-1, -1};
	eth.customSounds[CSND_MG42_FAR] = (soundReplace_t) {"sound/weapons/mg42/mg42_far.wav",-1, -1};
	eth.customSounds[CSND_MG42_FIRE] = (soundReplace_t) {"sound/weapons/mg42/mg42_fire.wav",-1, -1};
	eth.customSounds[CSND_MG42_HEAT] = (soundReplace_t) {"sound/weapons/mg42/mg42_heat.wav",-1, -1};
	eth.customSounds[CSND_MG42_RELOAD] = (soundReplace_t) {"sound/weapons/mg42/mg42_reload.wav",-1, -1};
	eth.customSounds[CSND_MP40_FIRE] = (soundReplace_t) {"sound/weapons/mp40/mp40_fire.wav",-1, -1};
	eth.customSounds[CSND_MP40_FAR] = (soundReplace_t) {"sound/weapons/mp40/mp40_far.wav",-1, -1};
	eth.customSounds[CSND_THOMPSON_FIRE] = (soundReplace_t) {"sound/weapons/thompson/thompson_fire.wav",-1, -1};
	eth.customSounds[CSND_THOMPSON_FAR] = (soundReplace_t) {"sound/weapons/thompson/thompson_far.wav",-1, -1};
	eth.customSounds[CSND_THOMPSON_REL] = (soundReplace_t) {"sound/weapons/thompson/thompson_reload.wav",-1, -1};
	eth.customSounds[CSND_STEN_FIRE] = (soundReplace_t) {"sound/weapons/sten/sten_fire.wav",-1, -1};
}

void registerEthMedias() {
	// Register all shaders chams
	#include "shaders.h"

	// Custom models/skins
	eth.pigHeadModel = orig_syscall(CG_R_REGISTERMODEL, "models/players/hud/pig.md3");
	eth.pigHeadSkin = orig_syscall(CG_R_REGISTERSKIN, "models/players/hud/pig.skin");

	// Irc fireteam team pin
	eth.bg_alliedpin = syscall_CG_R_RegisterShaderNoMip("gfx/2d/pin_allied");
	eth.bg_axispin = syscall_CG_R_RegisterShaderNoMip("gfx/2d/pin_axis");
	
	// All fonts used
	orig_syscall(CG_R_REGISTERFONT, "ariblk", 27, &eth.fontVariable);
	orig_syscall(CG_R_REGISTERFONT, "courbd", 21, &eth.fontFixed);

	// Custom HUD gfx, fonts
	registerHudStuff();
	
	// ----- Custom sounds -----
	// Misc sound
	eth.sounds[SOUND_HUMILIATION] = syscall_CG_S_RegisterSound("sound/misc/humiliation.wav", qfalse);
	eth.sounds[SOUND_PREPARE] = syscall_CG_S_RegisterSound("sound/misc/prepare.wav", qfalse);
	eth.sounds[SOUND_HEADSHOT1] = syscall_CG_S_RegisterSound("sound/misc/headshot1.wav", qfalse);
	eth.sounds[SOUND_HEADSHOT2] = syscall_CG_S_RegisterSound("sound/misc/headshot2.wav", qfalse);
	// Spree sound
	// level 1
	eth.sounds[SOUND_DOUBLEKILL1] = syscall_CG_S_RegisterSound("sound/spree/level1/doublekill1.wav", qfalse);
	eth.sounds[SOUND_EXCELLENT] = syscall_CG_S_RegisterSound("sound/spree/level1/excelent.wav", qfalse);
	eth.sounds[SOUND_IMPRESSIVE] = syscall_CG_S_RegisterSound("sound/spree/level1/impressive.wav", qfalse);
	eth.sounds[SOUND_KILLINGSPREE1] = syscall_CG_S_RegisterSound("sound/spree/level1/killingspree1.wav", qfalse);
	eth.sounds[SOUND_KILLINGSPREE2] = syscall_CG_S_RegisterSound("sound/spree/level1/killingspree2.wav", qfalse);
	eth.sounds[SOUND_PERFECT] = syscall_CG_S_RegisterSound("sound/spree/level1/perfect.wav", qfalse);
	// level 2
	eth.sounds[SOUND_GODLIKE1] = syscall_CG_S_RegisterSound("sound/spree/level2/godlike1.wav", qfalse);
	eth.sounds[SOUND_GODLIKE2] = syscall_CG_S_RegisterSound("sound/spree/level2/godlike2.wav", qfalse);
	eth.sounds[SOUND_HOLYSHIT] = syscall_CG_S_RegisterSound("sound/spree/level2/holyshit.wav", qfalse);
	eth.sounds[SOUND_MULTIKILL1] = syscall_CG_S_RegisterSound("sound/spree/level2/multikill1.wav", qfalse);
	eth.sounds[SOUND_MULTIKILL2] = syscall_CG_S_RegisterSound("sound/spree/level2/multikill2.wav", qfalse);
	eth.sounds[SOUND_MULTIKILL3] = syscall_CG_S_RegisterSound("sound/spree/level2/multikill3.wav", qfalse);
	eth.sounds[SOUND_TRIPLEKILL] = syscall_CG_S_RegisterSound("sound/spree/level2/tripplekill.wav", qfalse);
	// level 3
	eth.sounds[SOUND_DOMINATING1] = syscall_CG_S_RegisterSound("sound/spree/level3/dominating1.wav", qfalse);
	eth.sounds[SOUND_DOMINATING2] = syscall_CG_S_RegisterSound("sound/spree/level3/dominating2.wav", qfalse);
	eth.sounds[SOUND_ULTRAKILL1] = syscall_CG_S_RegisterSound("sound/spree/level3/ultrakill1.wav", qfalse);
	eth.sounds[SOUND_ULTRAKILL2] = syscall_CG_S_RegisterSound("sound/spree/level3/ultrakill2.wav", qfalse);
	eth.sounds[SOUND_ULTRAKILL3] = syscall_CG_S_RegisterSound("sound/spree/level3/ultrakill3.wav", qfalse);
	// level 4
	eth.sounds[SOUND_MONSTERKILL1] = syscall_CG_S_RegisterSound("sound/spree/level4/monsterkill1.wav", qfalse);
	eth.sounds[SOUND_MONSTERKILL2] = syscall_CG_S_RegisterSound("sound/spree/level4/monsterkill2.wav", qfalse);
	eth.sounds[SOUND_UNREAL] = syscall_CG_S_RegisterSound("sound/spree/level4/unreal.wav", qfalse);
	eth.sounds[SOUND_UNSTOPPABLE1] = syscall_CG_S_RegisterSound("sound/spree/level4/unstoppable1.wav", qfalse);
	eth.sounds[SOUND_UNSTOPPABLE2] = syscall_CG_S_RegisterSound("sound/spree/level4/unstoppable2.wav", qfalse);
	eth.sounds[SOUND_WICKEDSICK] = syscall_CG_S_RegisterSound("sound/spree/level4/wickedsick.wav", qfalse);
	// custom weapon sounds

	eth.sounds[SOUND_BROWNING_FIRE] = syscall_CG_S_RegisterSound("sound/weapons/browning/c_browning_fire.wav", qfalse);
	eth.sounds[SOUND_COLT_FAR] = syscall_CG_S_RegisterSound("sound/weapons/colt/c_colt_far.wav", qfalse);
	eth.sounds[SOUND_COLT_FIRE] = syscall_CG_S_RegisterSound("sound/weapons/colt/c_colt_fire.wav", qfalse);
	eth.sounds[SOUND_COLT_RELOAD] = syscall_CG_S_RegisterSound("sound/weapons/colt/c_colt_reload.wav", qfalse);
	eth.sounds[SOUND_COLT_SILENCE] = syscall_CG_S_RegisterSound("sound/weapons/colt/c_colt_silence.wav", qfalse);
	eth.sounds[SOUND_FG42_FIRE] = syscall_CG_S_RegisterSound("sound/weapons/fg42/c_fg42_fire.wav", qfalse);
	eth.sounds[SOUND_M1_FIREGRN] = syscall_CG_S_RegisterSound("sound/weapons/garand/c_m1_fire_grenade.wav", qfalse);
	eth.sounds[SOUND_M1_FIRE] = syscall_CG_S_RegisterSound("sound/weapons/garand/c_m1_fire.wav", qfalse);
	eth.sounds[SOUND_K43_FIRE] = syscall_CG_S_RegisterSound("sound/weapons/k43/c_k43_fire.wav", qfalse);
	eth.sounds[SOUND_MINE_STEP] = syscall_CG_S_RegisterSound("sound/weapons/landmine/c_mine_on.wav", qfalse);
	eth.sounds[SOUND_LUGER_FIRE] = syscall_CG_S_RegisterSound("sound/weapons/luger/c_luger_fire.wav", qfalse);
	eth.sounds[SOUND_LUGER_FAR] = syscall_CG_S_RegisterSound("sound/weapons/luger/c_luger_far.wav", qfalse);
	eth.sounds[SOUND_LUGER_SLND] = syscall_CG_S_RegisterSound("sound/weapons/luger/c_luger_silence.wav", qfalse);
	eth.sounds[SOUND_MG42_FAR] = syscall_CG_S_RegisterSound("sound/weapons/mg42/c_mg42_far.wav", qfalse);
	eth.sounds[SOUND_MG42_FIRE] = syscall_CG_S_RegisterSound("sound/weapons/mg42/c_mg42_fire.wav", qfalse);
	eth.sounds[SOUND_MG42_HEAT] = syscall_CG_S_RegisterSound("sound/weapons/mg42/c_mg42_heat.wav", qfalse);
	eth.sounds[SOUND_MG42_RELOAD] = syscall_CG_S_RegisterSound("sound/weapons/mg42/c_mg42_reload.wav", qfalse);
	eth.sounds[SOUND_MP40_FIRE] = syscall_CG_S_RegisterSound("sound/weapons/mp40/c_mp40_fire.wav", qfalse);
	eth.sounds[SOUND_MP40_FAR] = syscall_CG_S_RegisterSound("sound/weapons/mp40/c_mp40_far.wav", qfalse);
	eth.sounds[SOUND_THOMPSON_FIRE] = syscall_CG_S_RegisterSound("sound/weapons/thompson/c_thompson_fire.wav", qfalse);
	eth.sounds[SOUND_THOMPSON_FAR] = syscall_CG_S_RegisterSound("sound/weapons/thompson/c_thompson_far.wav", qfalse);
	eth.sounds[SOUND_THOMPSON_REL] = syscall_CG_S_RegisterSound("sound/weapons/thompson/c_thompson_reload.wav", qfalse);
	eth.sounds[SOUND_STEN_FIRE] = syscall_CG_S_RegisterSound("sound/weapons/sten/c_sten_fire.wav", qfalse);

	// Rank Icons esp
	eth.rankIcons[0] = syscall_CG_R_RegisterShaderNoMip("gfx/loading/pin_neutral");
	eth.rankIcons[1] = syscall_CG_R_RegisterShaderNoMip("gfx/loading/pin_neutral");
	eth.rankIcons[2] = syscall_CG_R_RegisterShaderNoMip("gfx/hud/ranks/rank2");
	eth.rankIcons[3] = syscall_CG_R_RegisterShaderNoMip("gfx/hud/ranks/rank3");
	eth.rankIcons[4] = syscall_CG_R_RegisterShaderNoMip("gfx/hud/ranks/rank4");
	eth.rankIcons[5] = syscall_CG_R_RegisterShaderNoMip("gfx/hud/ranks/rank5");
	eth.rankIcons[6] = syscall_CG_R_RegisterShaderNoMip("gfx/hud/ranks/rank6");
	eth.rankIcons[7] = syscall_CG_R_RegisterShaderNoMip("gfx/hud/ranks/rank7");
	eth.rankIcons[8] = syscall_CG_R_RegisterShaderNoMip("gfx/hud/ranks/rank8");
	eth.rankIcons[9] = syscall_CG_R_RegisterShaderNoMip("gfx/hud/ranks/rank9");
	eth.rankIcons[10] = syscall_CG_R_RegisterShaderNoMip("gfx/hud/ranks/rank10");
	eth.rankIcons[11] = syscall_CG_R_RegisterShaderNoMip("gfx/hud/ranks/rank11");

	// Class Icons esp
	eth.classIcons[PC_SOLDIER] = syscall_CG_R_RegisterShaderNoMip("gfx/limbo/ic_soldier");
	eth.classIcons[PC_MEDIC] = syscall_CG_R_RegisterShaderNoMip("gfx/limbo/ic_medic");
	eth.classIcons[PC_ENGINEER] = syscall_CG_R_RegisterShaderNoMip("gfx/limbo/ic_engineer");
	eth.classIcons[PC_FIELDOPS] = syscall_CG_R_RegisterShaderNoMip("gfx/limbo/ic_fieldops");
	eth.classIcons[PC_COVERTOPS] = syscall_CG_R_RegisterShaderNoMip("gfx/limbo/ic_covertops");

	// Weapon Icons esp
	eth.weaponIcons[MOD_BROWNING] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_browning_1_select");
	eth.weaponIcons[WP_MORTAR] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_mortar_1_select");
	eth.weaponIcons[WP_AKIMBO_SILENCEDLUGER] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_colt_1_select");
	eth.weaponIcons[WP_AKIMBO_LUGER] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_colt_1_select");
	eth.weaponIcons[WP_AKIMBO_COLT] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_colt_1_select");
	eth.weaponIcons[WP_AKIMBO_SILENCEDCOLT] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_colt_1_select");
	eth.weaponIcons[WP_NONE] = syscall_CG_R_RegisterShaderNoMip("icons/noammo");
	eth.weaponIcons[WP_SMOKE_MARKER] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_smokegrenade_1_select");
	eth.weaponIcons[WP_SMOKETRAIL] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_smokegrenade_1_select");
	eth.weaponIcons[WP_MAPMORTAR] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_grenade_1_select");
	eth.weaponIcons[WP_ARTY] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_syringe_1_select");
	eth.weaponIcons[WP_K43_SCOPE] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_mauser_1_select");
	eth.weaponIcons[WP_GPG40] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_kar98_1_select");
	eth.weaponIcons[WP_M7] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_m1_garand_1_select");
	eth.weaponIcons[WP_GARAND_SCOPE] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_mauser_1_select");
	eth.weaponIcons[WP_FG42SCOPE] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_fg42_1_select");
	eth.weaponIcons[WP_MORTAR_SET] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_mortar_1_select");
	eth.weaponIcons[WP_SMOKE_BOMB] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_dynamite_1_select");
	eth.weaponIcons[WP_TRIPMINE] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_dynamite_1_select");
	eth.weaponIcons[WP_MOBILE_MG42_SET] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_mg42_1_select");
	eth.weaponIcons[WP_SILENCED_COLT] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_colt_1_select");
	eth.weaponIcons[WP_MEDKIT] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_medheal_select");
	eth.weaponIcons[WP_MOBILE_MG42] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_mg42_1_select");
	eth.weaponIcons[WP_THOMPSON] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_thompson_1_select");
	eth.weaponIcons[WP_KNIFE] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_knife_1_select");
	eth.weaponIcons[WP_LUGER] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_luger_1_select");
	eth.weaponIcons[WP_MP40] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_MP40_1_select");
	eth.weaponIcons[WP_GRENADE_LAUNCHER] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_grenade_1_select");
	eth.weaponIcons[WP_PANZERFAUST] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_panzerfaust_1_select");
	eth.weaponIcons[WP_FLAMETHROWER] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_flamethrower_1_select");
	eth.weaponIcons[WP_COLT] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_colt_1_select");
	eth.weaponIcons[WP_GRENADE_PINEAPPLE] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_pineapple_1_select");
	eth.weaponIcons[WP_STEN] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_sten_1_select");
	eth.weaponIcons[WP_MEDIC_SYRINGE] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_syringe_1_select");
	eth.weaponIcons[WP_AMMO] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_ammopack_1_select");
	eth.weaponIcons[WP_SILENCER] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_silencer_1_select");
	eth.weaponIcons[WP_DYNAMITE] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_dynamite_1_select");
	eth.weaponIcons[WP_MEDKIT] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_medheal_1_select");
	eth.weaponIcons[WP_BINOCULARS] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_binoculars_1_select");
	eth.weaponIcons[WP_PLIERS] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_pliers_1_select");
	eth.weaponIcons[WP_KAR98] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_kar98_1_select");
	eth.weaponIcons[WP_CARBINE] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_mauser_1_select");
	eth.weaponIcons[WP_GARAND] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_m1_garand_1_select");
	eth.weaponIcons[WP_LANDMINE] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_landmine_1_select");
	eth.weaponIcons[WP_SATCHEL] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_satchel_1_select");
	eth.weaponIcons[WP_SATCHEL_DET] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_radio_1_select");
	eth.weaponIcons[WP_K43] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_mauser_1_select");
	eth.weaponIcons[WP_FG42] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_fg42_1_select");
	eth.weaponIcons[WP_MEDIC_ADRENALINE] = syscall_CG_R_RegisterShaderNoMip("icons/iconw_syringe_1_select");

	// Nice q3 numbers
	eth.number[0] = syscall_CG_R_RegisterShaderNoMip("gfx/2d/numbers/zero_32b");
	eth.number[1] = syscall_CG_R_RegisterShaderNoMip("gfx/2d/numbers/one_32b");
	eth.number[2] = syscall_CG_R_RegisterShaderNoMip("gfx/2d/numbers/two_32b");
	eth.number[3] = syscall_CG_R_RegisterShaderNoMip("gfx/2d/numbers/three_32b");
	eth.number[4] = syscall_CG_R_RegisterShaderNoMip("gfx/2d/numbers/four_32b");
	eth.number[5] = syscall_CG_R_RegisterShaderNoMip("gfx/2d/numbers/five_32b");
	eth.number[6] = syscall_CG_R_RegisterShaderNoMip("gfx/2d/numbers/six_32b");
	eth.number[7] = syscall_CG_R_RegisterShaderNoMip("gfx/2d/numbers/seven_32b");
	eth.number[8] = syscall_CG_R_RegisterShaderNoMip("gfx/2d/numbers/eight_32b");
	eth.number[9] = syscall_CG_R_RegisterShaderNoMip("gfx/2d/numbers/nine_32b");
    
	eth.dlightShader[0] = syscall_CG_R_RegisterShaderNoMip("gfx/effects/ethdlight");
}

// Would be better to check if a given gfx comes from a certain .pk3
// but no idea how to do that without lots of extra code, so this will do for now
char *pak0Sounds[] = {
	"sound/chat/allies/10a.wav",
	"sound/chat/allies/10b.wav",
	"sound/chat/allies/11a.wav",
	"sound/chat/allies/11b.wav",
	"sound/chat/allies/12a.wav",
	"sound/chat/allies/12b.wav",
	"sound/chat/allies/13a.wav",
	"sound/chat/allies/13b.wav",
	"sound/chat/allies/14a.wav",
	"sound/chat/allies/14b.wav",
	"sound/chat/allies/15a.wav",
	"sound/chat/allies/15b.wav",
	"sound/chat/allies/16a.wav",
	"sound/chat/allies/16b.wav",
	"sound/chat/allies/17a.wav",
	"sound/chat/allies/17b.wav",
	"sound/chat/allies/18a.wav",
	"sound/chat/allies/18b.wav",
	"sound/chat/allies/19a.wav",
	"sound/chat/allies/19b.wav",
	"sound/chat/allies/21a.wav",
	"sound/chat/allies/21b.wav",
	"sound/chat/allies/22a.wav",
	"sound/chat/allies/23a.wav",
	"sound/chat/allies/23b.wav",
	"sound/chat/allies/24a.wav",
	"sound/chat/allies/24b.wav",
	"sound/chat/allies/25a.wav",
	"sound/chat/allies/25b.wav",
	"sound/chat/allies/25c.wav",
	"sound/chat/allies/25d.wav",
	"sound/chat/allies/26a.wav",
	"sound/chat/allies/26b.wav",
	"sound/chat/allies/27a.wav",
	"sound/chat/allies/27b.wav",
	"sound/chat/allies/28a.wav",
	"sound/chat/allies/28b.wav",
	"sound/chat/allies/31a.wav",
	"sound/chat/allies/31b.wav",
	"sound/chat/allies/32a.wav",
	"sound/chat/allies/32b.wav",
	"sound/chat/allies/33a.wav",
	"sound/chat/allies/33b.wav",
	"sound/chat/allies/34a.wav",
	"sound/chat/allies/34b.wav",
	"sound/chat/allies/35a.wav",
	"sound/chat/allies/35b.wav",
	"sound/chat/allies/36a.wav",
	"sound/chat/allies/36b.wav",
	"sound/chat/allies/37a.wav",
	"sound/chat/allies/37b.wav",
	"sound/chat/allies/38a.wav",
	"sound/chat/allies/38b.wav",
	"sound/chat/allies/39a.wav",
	"sound/chat/allies/39b.wav",
	"sound/chat/allies/41a.wav",
	"sound/chat/allies/41b.wav",
	"sound/chat/allies/41c.wav",
	"sound/chat/allies/42a.wav",
	"sound/chat/allies/42b.wav",
	"sound/chat/allies/42c.wav",
	"sound/chat/allies/42d.wav",
	"sound/chat/allies/43a.wav",
	"sound/chat/allies/43b.wav",
	"sound/chat/allies/43c.wav",
	"sound/chat/allies/43d.wav",
	"sound/chat/allies/44a.wav",
	"sound/chat/allies/44b.wav",
	"sound/chat/allies/44c.wav",
	"sound/chat/allies/44d.wav",
	"sound/chat/allies/45a.wav",
	"sound/chat/allies/45b.wav",
	"sound/chat/allies/45c.wav",
	"sound/chat/allies/46a.wav",
	"sound/chat/allies/46b.wav",
	"sound/chat/allies/46c.wav",
	"sound/chat/allies/54a.wav",
	"sound/chat/allies/54b.wav",
	"sound/chat/allies/54c.wav",
	"sound/chat/allies/54d.wav",
	"sound/chat/allies/54e.wav",
	"sound/chat/allies/55a.wav",
	"sound/chat/allies/55b.wav",
	"sound/chat/allies/55c.wav",
	"sound/chat/allies/55d.wav",
	"sound/chat/allies/55e.wav",
	"sound/chat/allies/56a.wav",
	"sound/chat/allies/56b.wav",
	"sound/chat/allies/57a.wav",
	"sound/chat/allies/57b.wav",
	"sound/chat/allies/57c.wav",
	"sound/chat/allies/57d.wav",
	"sound/chat/allies/57e.wav",
	"sound/chat/allies/57f.wav",
	"sound/chat/allies/57g.wav",
	"sound/chat/allies/57h.wav",
	"sound/chat/allies/57i.wav",
	"sound/chat/allies/57j.wav",
	"sound/chat/allies/57k.wav",
	"sound/chat/allies/57l.wav",
	"sound/chat/allies/586a.wav",
	"sound/chat/allies/586b.wav",
	"sound/chat/allies/586c.wav",
	"sound/chat/allies/61a.wav",
	"sound/chat/allies/61b.wav",
	"sound/chat/allies/62a.wav",
	"sound/chat/allies/62b.wav",
	"sound/chat/allies/63a.wav",
	"sound/chat/allies/63b.wav",
	"sound/chat/allies/64a.wav",
	"sound/chat/allies/65a.wav",
	"sound/chat/allies/71a.wav",
	"sound/chat/allies/71b.wav",
	"sound/chat/allies/72a.wav",
	"sound/chat/allies/72b.wav",
	"sound/chat/allies/73a.wav",
	"sound/chat/allies/73b.wav",
	"sound/chat/allies/75a.wav",
	"sound/chat/allies/75b.wav",
	"sound/chat/allies/76a.wav",
	"sound/chat/allies/76b.wav",
	"sound/chat/allies/77a.wav",
	"sound/chat/allies/77b.wav",
	"sound/chat/allies/81a.wav",
	"sound/chat/allies/81b.wav",
	"sound/chat/allies/81c.wav",
	"sound/chat/allies/81d.wav",
	"sound/chat/allies/82a.wav",
	"sound/chat/allies/82b.wav",
	"sound/chat/allies/82c.wav",
	"sound/chat/allies/82d.wav",
	"sound/chat/allies/83a.wav",
	"sound/chat/allies/83b.wav",
	"sound/chat/allies/84a.wav",
	"sound/chat/allies/84b.wav",
	"sound/chat/allies/911a.wav",
	"sound/chat/allies/911b.wav",
	"sound/chat/allies/921a.wav",
	"sound/chat/allies/921b.wav",
	"sound/chat/allies/922a.wav",
	"sound/chat/allies/923a.wav",
	"sound/chat/allies/923b.wav",
	"sound/chat/allies/924a.wav",
	"sound/chat/allies/924b.wav",
	"sound/chat/allies/931a.wav",
	"sound/chat/allies/931b.wav",
	"sound/chat/allies/932a.wav",
	"sound/chat/allies/932b.wav",
	"sound/chat/allies/933a.wav",
	"sound/chat/allies/933b.wav",
	"sound/chat/allies/934a.wav",
	"sound/chat/allies/934b.wav",
	"sound/chat/allies/935a.wav",
	"sound/chat/allies/935b.wav",
	"sound/chat/allies/941a.wav",
	"sound/chat/allies/941b.wav",
	"sound/chat/allies/942a.wav",
	"sound/chat/allies/942b.wav",
	"sound/chat/allies/944a.wav",
	"sound/chat/allies/944b.wav",
	"sound/chat/allies/945a.wav",
	"sound/chat/allies/945b.wav",
	"sound/chat/allies/951a.wav",
	"sound/chat/allies/951b.wav",
	"sound/chat/allies/952a.wav",
	"sound/chat/allies/953a.wav",
	"sound/chat/allies/953b.wav",
	"sound/chat/allies/954a.wav",
	"sound/chat/allies/955a.wav",
	"sound/chat/allies/98a.wav",
	"sound/chat/allies/98b.wav",
	"sound/chat/allies/99a.wav",
	"sound/chat/allies/99b.wav",
	"sound/chat/allies/medic.wav",
	"sound/chat/axis/10a.wav",
	"sound/chat/axis/10b.wav",
	"sound/chat/axis/11a.wav",
	"sound/chat/axis/11b.wav",
	"sound/chat/axis/12a.wav",
	"sound/chat/axis/12b.wav",
	"sound/chat/axis/13a.wav",
	"sound/chat/axis/13b.wav",
	"sound/chat/axis/14a.wav",
	"sound/chat/axis/14b.wav",
	"sound/chat/axis/15a.wav",
	"sound/chat/axis/15b.wav",
	"sound/chat/axis/16a.wav",
	"sound/chat/axis/16b.wav",
	"sound/chat/axis/17a.wav",
	"sound/chat/axis/17b.wav",
	"sound/chat/axis/18a.wav",
	"sound/chat/axis/18b.wav",
	"sound/chat/axis/19a.wav",
	"sound/chat/axis/19b.wav",
	"sound/chat/axis/21a.wav",
	"sound/chat/axis/21b.wav",
	"sound/chat/axis/22a.wav",
	"sound/chat/axis/23a.wav",
	"sound/chat/axis/23b.wav",
	"sound/chat/axis/24a.wav",
	"sound/chat/axis/24b.wav",
	"sound/chat/axis/25a.wav",
	"sound/chat/axis/25b.wav",
	"sound/chat/axis/25c.wav",
	"sound/chat/axis/25d.wav",
	"sound/chat/axis/26a.wav",
	"sound/chat/axis/26b.wav",
	"sound/chat/axis/27a.wav",
	"sound/chat/axis/27b.wav",
	"sound/chat/axis/28a.wav",
	"sound/chat/axis/28b.wav",
	"sound/chat/axis/31a.wav",
	"sound/chat/axis/31b.wav",
	"sound/chat/axis/32a.wav",
	"sound/chat/axis/32b.wav",
	"sound/chat/axis/33a.wav",
	"sound/chat/axis/33b.wav",
	"sound/chat/axis/34a.wav",
	"sound/chat/axis/34b.wav",
	"sound/chat/axis/35a.wav",
	"sound/chat/axis/35b.wav",
	"sound/chat/axis/36a.wav",
	"sound/chat/axis/36b.wav",
	"sound/chat/axis/37a.wav",
	"sound/chat/axis/37b.wav",
	"sound/chat/axis/38a.wav",
	"sound/chat/axis/38b.wav",
	"sound/chat/axis/39a.wav",
	"sound/chat/axis/39b.wav",
	"sound/chat/axis/41a.wav",
	"sound/chat/axis/41b.wav",
	"sound/chat/axis/41c.wav",
	"sound/chat/axis/42a.wav",
	"sound/chat/axis/42b.wav",
	"sound/chat/axis/42c.wav",
	"sound/chat/axis/43a.wav",
	"sound/chat/axis/43b.wav",
	"sound/chat/axis/43c.wav",
	"sound/chat/axis/44a.wav",
	"sound/chat/axis/44b.wav",
	"sound/chat/axis/44c.wav",
	"sound/chat/axis/45a.wav",
	"sound/chat/axis/45b.wav",
	"sound/chat/axis/46a.wav",
	"sound/chat/axis/46b.wav",
	"sound/chat/axis/54a.wav",
	"sound/chat/axis/54b.wav",
	"sound/chat/axis/54c.wav",
	"sound/chat/axis/55a.wav",
	"sound/chat/axis/55b.wav",
	"sound/chat/axis/55c.wav",
	"sound/chat/axis/56a.wav",
	"sound/chat/axis/56b.wav",
	"sound/chat/axis/57a.wav",
	"sound/chat/axis/57b.wav",
	"sound/chat/axis/57c.wav",
	"sound/chat/axis/57d.wav",
	"sound/chat/axis/57e.wav",
	"sound/chat/axis/57f.wav",
	"sound/chat/axis/57g.wav",
	"sound/chat/axis/57h.wav",
	"sound/chat/axis/586a.wav",
	"sound/chat/axis/586b.wav",
	"sound/chat/axis/61a.wav",
	"sound/chat/axis/61b.wav",
	"sound/chat/axis/62a.wav",
	"sound/chat/axis/62b.wav",
	"sound/chat/axis/63a.wav",
	"sound/chat/axis/63b.wav",
	"sound/chat/axis/64a.wav",
	"sound/chat/axis/64b.wav",
	"sound/chat/axis/65a.wav",
	"sound/chat/axis/71a.wav",
	"sound/chat/axis/71b.wav",
	"sound/chat/axis/72a.wav",
	"sound/chat/axis/72b.wav",
	"sound/chat/axis/73a.wav",
	"sound/chat/axis/73b.wav",
	"sound/chat/axis/75a.wav",
	"sound/chat/axis/75b.wav",
	"sound/chat/axis/76a.wav",
	"sound/chat/axis/76b.wav",
	"sound/chat/axis/77a.wav",
	"sound/chat/axis/77b.wav",
	"sound/chat/axis/81a.wav",
	"sound/chat/axis/81b.wav",
	"sound/chat/axis/82a.wav",
	"sound/chat/axis/82b.wav",
	"sound/chat/axis/83a.wav",
	"sound/chat/axis/83b.wav",
	"sound/chat/axis/84a.wav",
	"sound/chat/axis/84b.wav",
	"sound/chat/axis/911a.wav",
	"sound/chat/axis/911b.wav",
	"sound/chat/axis/921a.wav",
	"sound/chat/axis/921b.wav",
	"sound/chat/axis/922a.wav",
	"sound/chat/axis/922b.wav",
	"sound/chat/axis/923a.wav",
	"sound/chat/axis/923b.wav",
	"sound/chat/axis/924a.wav",
	"sound/chat/axis/924b.wav",
	"sound/chat/axis/931a.wav",
	"sound/chat/axis/931b.wav",
	"sound/chat/axis/932a.wav",
	"sound/chat/axis/932b.wav",
	"sound/chat/axis/933a.wav",
	"sound/chat/axis/933b.wav",
	"sound/chat/axis/934a.wav",
	"sound/chat/axis/934b.wav",
	"sound/chat/axis/935a.wav",
	"sound/chat/axis/935b.wav",
	"sound/chat/axis/941a.wav",
	"sound/chat/axis/941b.wav",
	"sound/chat/axis/942a.wav",
	"sound/chat/axis/942b.wav",
	"sound/chat/axis/944a.wav",
	"sound/chat/axis/944b.wav",
	"sound/chat/axis/945a.wav",
	"sound/chat/axis/945b.wav",
	"sound/chat/axis/951a.wav",
	"sound/chat/axis/951b.wav",
	"sound/chat/axis/952a.wav",
	"sound/chat/axis/952b.wav",
	"sound/chat/axis/953a.wav",
	"sound/chat/axis/953b.wav",
	"sound/chat/axis/954a.wav",
	"sound/chat/axis/954b.wav",
	"sound/chat/axis/955a.wav",
	"sound/chat/axis/955b.wav",
	"sound/chat/axis/98a.wav",
	"sound/chat/axis/98b.wav",
	"sound/chat/axis/98c.wav",
	"sound/chat/axis/99a.wav",
	"sound/chat/axis/medic.wav",
	"sound/maps/expl_large.wav",
	"sound/maps/expl_med.wav",
	"sound/maps/expl_small.wav",
	"sound/maps/gun_fire.wav",
	"sound/maps/track_move.wav",
	"sound/maps/track_switch.wav",
	"sound/menu/cancel.wav",
	"sound/menu/filter.wav",
	"sound/menu/select.wav",
	"sound/misc/am_pkup.wav",
	"sound/misc/bag_toss.wav",
	"sound/misc/body_pickup.wav",
	"sound/misc/health_pickup.wav",
	"sound/misc/rank_up.wav",
	"sound/misc/referee.wav",
	"sound/misc/skill_up.wav",
	"sound/misc/vote.wav",
	"sound/misc/vo_revive.wav",
	"sound/misc/w_pkup.wav",
	"sound/movers/doors/default_door_locked.wav",
	"sound/movers/doors/door2_close.wav",
	"sound/movers/doors/door2_locked.wav",
	"sound/movers/doors/door2_open.wav",
	"sound/movers/doors/door4_close.wav",
	"sound/movers/doors/door4_closeq.wav",
	"sound/movers/doors/door4_endc.wav",
	"sound/movers/doors/door4_endcq.wav",
	"sound/movers/doors/door4_kicked.wav",
	"sound/movers/doors/door4_kickedend.wav",
	"sound/movers/doors/door4_locked.wav",
	"sound/movers/doors/door4_open.wav",
	"sound/movers/doors/door4_openq.wav",
	"sound/movers/doors/door5_close.wav",
	"sound/movers/doors/door5_endc.wav",
	"sound/movers/doors/door5_kicked.wav",
	"sound/movers/doors/door5_kickedend.wav",
	"sound/movers/doors/door5_locked.wav",
	"sound/movers/doors/door5_open.wav",
	"sound/movers/doors/door6_close.wav",
	"sound/movers/doors/door6_endc.wav",
	"sound/movers/doors/door6_locked.wav",
	"sound/movers/doors/door6_loopc.wav",
	"sound/movers/doors/door6_loopo.wav",
	"sound/movers/doors/door6_open.wav",
	"sound/movers/misc/big_gate1.wav",
	"sound/movers/misc/big_gate2.wav",
	"sound/movers/misc/big_gate3.wav",
	"sound/movers/misc/garage_door_end_01.wav",
	"sound/movers/misc/garage_door_loop_01.wav",
	"sound/movers/misc/garage_door_start_01.wav",
	"sound/movers/motors/motor_end_01.wav",
	"sound/movers/motors/motor_end_02.wav",
	"sound/movers/motors/motor_loop_01.wav",
	"sound/movers/motors/motor_loop_02.wav",
	"sound/movers/motors/motor_loop_03.wav",
	"sound/movers/motors/motor_start_01.wav",
	"sound/movers/motors/motor_start_02.wav",
	"sound/movers/switches/butn2.wav",
	"sound/movers/switches/switch.wav",
	"sound/movers/switches/switch_01.wav",
	"sound/movers/switches/switch_02.wav",
	"sound/music/allies_win.wav",
	"sound/music/axis_win.wav",
	"sound/music/menu_server.wav",
	"sound/player/default/blank.wav",
	"sound/player/footsteps/carpet1.wav",
	"sound/player/footsteps/carpet2.wav",
	"sound/player/footsteps/carpet3.wav",
	"sound/player/footsteps/carpet4.wav",
	"sound/player/footsteps/carpet_jump.wav",
	"sound/player/footsteps/grass1.wav",
	"sound/player/footsteps/grass2.wav",
	"sound/player/footsteps/grass3.wav",
	"sound/player/footsteps/grass4.wav",
	"sound/player/footsteps/grass_jump.wav",
	"sound/player/footsteps/gravel1.wav",
	"sound/player/footsteps/gravel2.wav",
	"sound/player/footsteps/gravel3.wav",
	"sound/player/footsteps/gravel4.wav",
	"sound/player/footsteps/gravel_jump.wav",
	"sound/player/footsteps/metal1.wav",
	"sound/player/footsteps/metal2.wav",
	"sound/player/footsteps/metal3.wav",
	"sound/player/footsteps/metal4.wav",
	"sound/player/footsteps/metal_jump.wav",
	"sound/player/footsteps/roof1.wav",
	"sound/player/footsteps/roof2.wav",
	"sound/player/footsteps/roof3.wav",
	"sound/player/footsteps/roof4.wav",
	"sound/player/footsteps/roof_jump.wav",
	"sound/player/footsteps/snow1.wav",
	"sound/player/footsteps/snow2.wav",
	"sound/player/footsteps/snow3.wav",
	"sound/player/footsteps/snow4.wav",
	"sound/player/footsteps/snow_jump.wav",
	"sound/player/footsteps/stone1.wav",
	"sound/player/footsteps/stone2.wav",
	"sound/player/footsteps/stone3.wav",
	"sound/player/footsteps/stone4.wav",
	"sound/player/footsteps/stone_jump.wav",
	"sound/player/footsteps/water1.wav",
	"sound/player/footsteps/water2.wav",
	"sound/player/footsteps/water3.wav",
	"sound/player/footsteps/water4.wav",
	"sound/player/footsteps/water_jump.wav",
	"sound/player/footsteps/wood1.wav",
	"sound/player/footsteps/wood2.wav",
	"sound/player/footsteps/wood3.wav",
	"sound/player/footsteps/wood4.wav",
	"sound/player/footsteps/wood_jump.wav",
	"sound/player/gasp.wav",
	"sound/player/gib.wav",
	"sound/player/gurp1.wav",
	"sound/player/gurp2.wav",
	"sound/player/hurt_barbwire.wav",
	"sound/player/land_hurt.wav",
	"sound/player/underwater.wav",
	"sound/player/water_in.wav",
	"sound/player/water_out.wav",
	"sound/player/water_un.wav",
	"sound/vehicles/misc/radar_end.wav",
	"sound/vehicles/misc/radar_loop.wav",
	"sound/vehicles/misc/radar_start.wav",
	"sound/vehicles/tank/tank_fire.wav",
	"sound/vehicles/tank/tank_idle.wav",
	"sound/vehicles/tank/tank_move.wav",
	"sound/vehicles/tank/tank_revdown.wav",
	"sound/vehicles/tank/tank_revup.wav",
	"sound/vehicles/tank/tank_start.wav",
	"sound/vehicles/tank/tank_stop.wav",
	"sound/vehicles/tank/turret_end.wav",
	"sound/vehicles/tank/turret_spin.wav",
	"sound/vehicles/truck/truck_idle.wav",
	"sound/vehicles/truck/truck_move.wav",
	"sound/vehicles/truck/truck_revdown.wav",
	"sound/vehicles/truck/truck_revup.wav",
	"sound/vehicles/truck/truck_start.wav",
	"sound/vehicles/truck/truck_stop.wav",
	"sound/vehicles/tug/tug_idle.wav",
	"sound/vehicles/tug/tug_move.wav",
	"sound/vo/battery/allies/hq_bunkercap.wav",
	"sound/vo/battery/allies/hq_bunkercapd.wav",
	"sound/vo/battery/allies/hq_bunkerrecl.wav",
	"sound/vo/battery/allies/hq_gendest.wav",
	"sound/vo/battery/allies/hq_gendyn.wav",
	"sound/vo/battery/allies/hq_gunctrldyn.wav",
	"sound/vo/battery/allies/hq_rampcon.wav",
	"sound/vo/battery/allies/hq_rampconst.wav",
	"sound/vo/battery/allies/hq_rampdest.wav",
	"sound/vo/battery/axis/hq_beacheadv.wav",
	"sound/vo/battery/axis/hq_beachwadv.wav",
	"sound/vo/battery/axis/hq_bunkercap.wav",
	"sound/vo/battery/axis/hq_bunkerdef.wav",
	"sound/vo/battery/axis/hq_bunkerrecl.wav",
	"sound/vo/battery/axis/hq_genconst.wav",
	"sound/vo/battery/axis/hq_gendef.wav",
	"sound/vo/battery/axis/hq_gendest.wav",
	"sound/vo/battery/axis/hq_gunctrldef.wav",
	"sound/vo/battery/axis/hq_rampconst.wav",
	"sound/vo/battery/axis/hq_rampdest.wav",
	"sound/vo/battery/axis/hq_rampstop.wav",
	"sound/vo/battery/news_battery.wav",
	"sound/vo/fueldump/allies/hq_bridgecon.wav",
	"sound/vo/fueldump/allies/hq_bridgeconst.wav",
	"sound/vo/fueldump/allies/hq_bridgedam.wav",
	"sound/vo/fueldump/allies/hq_bridgedest.wav",
	"sound/vo/fueldump/allies/hq_bridgereinf.wav",
	"sound/vo/fueldump/allies/hq_bridgereinfd.wav",
	"sound/vo/fueldump/allies/hq_depotdest.wav",
	"sound/vo/fueldump/allies/hq_depotdyn.wav",
	"sound/vo/fueldump/allies/hq_dumpdyn.wav",
	"sound/vo/fueldump/allies/hq_gatesdest.wav",
	"sound/vo/fueldump/allies/hq_gratedest.wav",
	"sound/vo/fueldump/allies/hq_tankbridge.wav",
	"sound/vo/fueldump/allies/hq_tankgates.wav",
	"sound/vo/fueldump/allies/hq_tankrear.wav",
	"sound/vo/fueldump/allies/hq_tunneldest.wav",
	"sound/vo/fueldump/allies/hq_walldest.wav",
	"sound/vo/fueldump/axis/hq_bridgeconst.wav",
	"sound/vo/fueldump/axis/hq_bridgedam.wav",
	"sound/vo/fueldump/axis/hq_bridgedest.wav",
	"sound/vo/fueldump/axis/hq_bridgereinf.wav",
	"sound/vo/fueldump/axis/hq_bridgerep.wav",
	"sound/vo/fueldump/axis/hq_bridgestop.wav",
	"sound/vo/fueldump/axis/hq_depotbreach.wav",
	"sound/vo/fueldump/axis/hq_depotcon.wav",
	"sound/vo/fueldump/axis/hq_depotconst.wav",
	"sound/vo/fueldump/axis/hq_depotdest.wav",
	"sound/vo/fueldump/axis/hq_dumpdef.wav",
	"sound/vo/fueldump/axis/hq_gatesdest.wav",
	"sound/vo/fueldump/axis/hq_gatesstop.wav",
	"sound/vo/fueldump/axis/hq_gratedest.wav",
	"sound/vo/fueldump/axis/hq_tankbridge.wav",
	"sound/vo/fueldump/axis/hq_tanktunnels.wav",
	"sound/vo/fueldump/axis/hq_tunneldest.wav",
	"sound/vo/fueldump/axis/hq_tunnelstop.wav",
	"sound/vo/fueldump/axis/hq_walldest.wav",
	"sound/vo/fueldump/axis/hq_wallstop.wav",
	"sound/vo/fueldump/news_fueldump.wav",
	"sound/vo/general/allies/hq_2minutes_a.wav",
	"sound/vo/general/allies/hq_2minutes_b.wav",
	"sound/vo/general/allies/hq_30seconds_a.wav",
	"sound/vo/general/allies/hq_30seconds_b.wav",
	"sound/vo/general/allies/hq_5minutes_a.wav",
	"sound/vo/general/allies/hq_5minutes_b.wav",
	"sound/vo/general/allies/hq_airabort_a.wav",
	"sound/vo/general/allies/hq_airabort_b.wav",
	"sound/vo/general/allies/hq_airdenied_a.wav",
	"sound/vo/general/allies/hq_airdenied_b.wav",
	"sound/vo/general/allies/hq_airstrike_a.wav",
	"sound/vo/general/allies/hq_airstrike_b.wav",
	"sound/vo/general/allies/hq_artabort_a.wav",
	"sound/vo/general/allies/hq_artabort_b.wav",
	"sound/vo/general/allies/hq_artdenied_a.wav",
	"sound/vo/general/allies/hq_artdenied_b.wav",
	"sound/vo/general/allies/hq_artillery_a.wav",
	"sound/vo/general/allies/hq_artillery_b.wav",
	"sound/vo/general/allies/hq_conconst_a.wav",
	"sound/vo/general/allies/hq_conconst_b.wav",
	"sound/vo/general/allies/hq_condest_a.wav",
	"sound/vo/general/allies/hq_condest_b.wav",
	"sound/vo/general/allies/hq_confail.wav",
	"sound/vo/general/allies/hq_cpconst2.wav",
	"sound/vo/general/allies/hq_cpconst_a.wav",
	"sound/vo/general/allies/hq_cpconst_b.wav",
	"sound/vo/general/allies/hq_cpcon_a.wav",
	"sound/vo/general/allies/hq_cpcon_b.wav",
	"sound/vo/general/allies/hq_cpdam.wav",
	"sound/vo/general/allies/hq_cprep.wav",
	"sound/vo/general/allies/hq_dyndefused2_a.wav",
	"sound/vo/general/allies/hq_dyndefused2_b.wav",
	"sound/vo/general/allies/hq_dyndefused_a.wav",
	"sound/vo/general/allies/hq_dyndefused_b.wav",
	"sound/vo/general/allies/hq_dynplanted2_a.wav",
	"sound/vo/general/allies/hq_dynplanted2_b.wav",
	"sound/vo/general/allies/hq_dynplanted_a.wav",
	"sound/vo/general/allies/hq_dynplanted_b.wav",
	"sound/vo/general/allies/hq_minesspot.wav",
	"sound/vo/general/allies/hq_needcos_a.wav",
	"sound/vo/general/allies/hq_needcos_b.wav",
	"sound/vo/general/allies/hq_needeng_a.wav",
	"sound/vo/general/allies/hq_needeng_b.wav",
	"sound/vo/general/allies/hq_needfos_a.wav",
	"sound/vo/general/allies/hq_needfos_b.wav",
	"sound/vo/general/allies/hq_needmedic_a.wav",
	"sound/vo/general/allies/hq_needmedic_b.wav",
	"sound/vo/general/allies/hq_needsoldier_a.wav",
	"sound/vo/general/allies/hq_needsoldier_b.wav",
	"sound/vo/general/allies/hq_objcap.wav",
	"sound/vo/general/allies/hq_objdest.wav",
	"sound/vo/general/allies/hq_objlost.wav",
	"sound/vo/general/allies/hq_objsec.wav",
	"sound/vo/general/allies/hq_objtaken.wav",
	"sound/vo/general/allies/hq_promocol.wav",
	"sound/vo/general/allies/hq_promocpl.wav",
	"sound/vo/general/allies/hq_promocpt.wav",
	"sound/vo/general/allies/hq_promogen.wav",
	"sound/vo/general/allies/hq_promogenbrig.wav",
	"sound/vo/general/allies/hq_promogenlt.wav",
	"sound/vo/general/allies/hq_promolt.wav",
	"sound/vo/general/allies/hq_promomaj.wav",
	"sound/vo/general/allies/hq_promopfc.wav",
	"sound/vo/general/allies/hq_promosgt.wav",
	"sound/vo/general/allies/hq_tankdam_a.wav",
	"sound/vo/general/allies/hq_tankdam_b.wav",
	"sound/vo/general/allies/hq_tankesc_a.wav",
	"sound/vo/general/allies/hq_tankesc_b.wav",
	"sound/vo/general/allies/hq_tankrep_a.wav",
	"sound/vo/general/allies/hq_tankrep_b.wav",
	"sound/vo/general/allies/hq_truckdam_a.wav",
	"sound/vo/general/allies/hq_truckdam_b.wav",
	"sound/vo/general/allies/hq_truckesc_a.wav",
	"sound/vo/general/allies/hq_truckesc_b.wav",
	"sound/vo/general/allies/hq_truckrep_a.wav",
	"sound/vo/general/allies/hq_truckrep_b.wav",
	"sound/vo/general/axis/hq_2minutes.wav",
	"sound/vo/general/axis/hq_30seconds.wav",
	"sound/vo/general/axis/hq_5minutes.wav",
	"sound/vo/general/axis/hq_airabort.wav",
	"sound/vo/general/axis/hq_airdenied.wav",
	"sound/vo/general/axis/hq_airstrike_a.wav",
	"sound/vo/general/axis/hq_airstrike_b.wav",
	"sound/vo/general/axis/hq_artabort.wav",
	"sound/vo/general/axis/hq_artdenied_a.wav",
	"sound/vo/general/axis/hq_artdenied_b.wav",
	"sound/vo/general/axis/hq_artillery_a.wav",
	"sound/vo/general/axis/hq_artillery_b.wav",
	"sound/vo/general/axis/hq_conconst_a.wav",
	"sound/vo/general/axis/hq_conconst_b.wav",
	"sound/vo/general/axis/hq_condest_a.wav",
	"sound/vo/general/axis/hq_condest_b.wav",
	"sound/vo/general/axis/hq_confail_a.wav",
	"sound/vo/general/axis/hq_confail_b.wav",
	"sound/vo/general/axis/hq_cpconst2_a.wav",
	"sound/vo/general/axis/hq_cpconst2_b.wav",
	"sound/vo/general/axis/hq_cpconst_a.wav",
	"sound/vo/general/axis/hq_cpconst_b.wav",
	"sound/vo/general/axis/hq_cpcon_a.wav",
	"sound/vo/general/axis/hq_cpcon_b.wav",
	"sound/vo/general/axis/hq_cpdam.wav",
	"sound/vo/general/axis/hq_cprep.wav",
	"sound/vo/general/axis/hq_dyndefused2_a.wav",
	"sound/vo/general/axis/hq_dyndefused2_b.wav",
	"sound/vo/general/axis/hq_dyndefused_a.wav",
	"sound/vo/general/axis/hq_dyndefused_b.wav",
	"sound/vo/general/axis/hq_dynplanted2_a.wav",
	"sound/vo/general/axis/hq_dynplanted2_b.wav",
	"sound/vo/general/axis/hq_dynplanted_a.wav",
	"sound/vo/general/axis/hq_dynplanted_b.wav",
	"sound/vo/general/axis/hq_minesspot.wav",
	"sound/vo/general/axis/hq_needcos_a.wav",
	"sound/vo/general/axis/hq_needcos_b.wav",
	"sound/vo/general/axis/hq_needeng_a.wav",
	"sound/vo/general/axis/hq_needeng_b.wav",
	"sound/vo/general/axis/hq_needfos_a.wav",
	"sound/vo/general/axis/hq_needfos_b.wav",
	"sound/vo/general/axis/hq_needmedic_a.wav",
	"sound/vo/general/axis/hq_needmedic_b.wav",
	"sound/vo/general/axis/hq_needsoldier_a.wav",
	"sound/vo/general/axis/hq_needsoldier_b.wav",
	"sound/vo/general/axis/hq_objcap.wav",
	"sound/vo/general/axis/hq_objdest.wav",
	"sound/vo/general/axis/hq_objlost.wav",
	"sound/vo/general/axis/hq_objsec.wav",
	"sound/vo/general/axis/hq_objtaken.wav",
	"sound/vo/general/axis/hq_promocol.wav",
	"sound/vo/general/axis/hq_promocpl.wav",
	"sound/vo/general/axis/hq_promocpt.wav",
	"sound/vo/general/axis/hq_promogen.wav",
	"sound/vo/general/axis/hq_promogenlt.wav",
	"sound/vo/general/axis/hq_promogenmaj.wav",
	"sound/vo/general/axis/hq_promolt.wav",
	"sound/vo/general/axis/hq_promomaj.wav",
	"sound/vo/general/axis/hq_promopfc.wav",
	"sound/vo/general/axis/hq_promosgt.wav",
	"sound/vo/general/axis/hq_tankdam_a.wav",
	"sound/vo/general/axis/hq_tankdam_b.wav",
	"sound/vo/general/axis/hq_tankrep_a.wav",
	"sound/vo/general/axis/hq_tankrep_b.wav",
	"sound/vo/general/axis/hq_tankstop_a.wav",
	"sound/vo/general/axis/hq_tankstop_b.wav",
	"sound/vo/general/axis/hq_truckdam_a.wav",
	"sound/vo/general/axis/hq_truckdam_b.wav",
	"sound/vo/general/axis/hq_truckrep_a.wav",
	"sound/vo/general/axis/hq_truckrep_b.wav",
	"sound/vo/general/axis/hq_truckstop_a.wav",
	"sound/vo/general/axis/hq_truckstop_b.wav",
	"sound/vo/goldrush/allies/hq_bankyard.wav",
	"sound/vo/goldrush/allies/hq_gold1lost.wav",
	"sound/vo/goldrush/allies/hq_gold1ret.wav",
	"sound/vo/goldrush/allies/hq_gold1sec.wav",
	"sound/vo/goldrush/allies/hq_gold1taken.wav",
	"sound/vo/goldrush/allies/hq_gold2lost.wav",
	"sound/vo/goldrush/allies/hq_gold2ret.wav",
	"sound/vo/goldrush/allies/hq_gold2sec.wav",
	"sound/vo/goldrush/allies/hq_gold2taken.wav",
	"sound/vo/goldrush/allies/hq_goldget.wav",
	"sound/vo/goldrush/allies/hq_tankbank.wav",
	"sound/vo/goldrush/allies/hq_tankbar1.wav",
	"sound/vo/goldrush/allies/hq_tankbar2.wav",
	"sound/vo/goldrush/allies/hq_tankbardest.wav",
	"sound/vo/goldrush/allies/hq_tankbardyn.wav",
	"sound/vo/goldrush/allies/hq_tankbarsdyn.wav",
	"sound/vo/goldrush/allies/hq_tanksteal.wav",
	"sound/vo/goldrush/allies/hq_tankstolen.wav",
	"sound/vo/goldrush/allies/hq_truckbar1.wav",
	"sound/vo/goldrush/allies/hq_truckbar2.wav",
	"sound/vo/goldrush/allies/hq_truckbardest.wav",
	"sound/vo/goldrush/allies/hq_truckbardyn.wav",
	"sound/vo/goldrush/allies/hq_truckbarsdyn.wav",
	"sound/vo/goldrush/allies/hq_trucksteal.wav",
	"sound/vo/goldrush/allies/hq_truckstolen.wav",
	"sound/vo/goldrush/axis/hq_bankbroken.wav",
	"sound/vo/goldrush/axis/hq_bankyard.wav",
	"sound/vo/goldrush/axis/hq_gold1lost.wav",
	"sound/vo/goldrush/axis/hq_gold1ret.wav",
	"sound/vo/goldrush/axis/hq_gold1sec.wav",
	"sound/vo/goldrush/axis/hq_gold1taken.wav",
	"sound/vo/goldrush/axis/hq_gold2lost.wav",
	"sound/vo/goldrush/axis/hq_gold2ret.wav",
	"sound/vo/goldrush/axis/hq_gold2sec.wav",
	"sound/vo/goldrush/axis/hq_gold2taken.wav",
	"sound/vo/goldrush/axis/hq_golddef.wav",
	"sound/vo/goldrush/axis/hq_tankbar1.wav",
	"sound/vo/goldrush/axis/hq_tankbar2.wav",
	"sound/vo/goldrush/axis/hq_tankbarcon.wav",
	"sound/vo/goldrush/axis/hq_tankbarconst.wav",
	"sound/vo/goldrush/axis/hq_tankbardest.wav",
	"sound/vo/goldrush/axis/hq_tankbarscon.wav",
	"sound/vo/goldrush/axis/hq_tanksteal.wav",
	"sound/vo/goldrush/axis/hq_tankstolen.wav",
	"sound/vo/goldrush/axis/hq_truckbar1.wav",
	"sound/vo/goldrush/axis/hq_truckbar2.wav",
	"sound/vo/goldrush/axis/hq_truckbarcon.wav",
	"sound/vo/goldrush/axis/hq_truckbarconst.wav",
	"sound/vo/goldrush/axis/hq_truckbardest.wav",
	"sound/vo/goldrush/axis/hq_truckbarscon.wav",
	"sound/vo/goldrush/axis/hq_trucksteal.wav",
	"sound/vo/goldrush/axis/hq_truckstolen.wav",
	"sound/vo/goldrush/news_goldrush.wav",
	"sound/vo/oasis/allies/hq_cavesdrain.wav",
	"sound/vo/oasis/allies/hq_cavesflood.wav",
	"sound/vo/oasis/allies/hq_citycap.wav",
	"sound/vo/oasis/allies/hq_citycapd.wav",
	"sound/vo/oasis/allies/hq_cityrecl.wav",
	"sound/vo/oasis/allies/hq_paknorthdest.wav",
	"sound/vo/oasis/allies/hq_paknorthdyn.wav",
	"sound/vo/oasis/allies/hq_paksdyn.wav",
	"sound/vo/oasis/allies/hq_paksouthdest.wav",
	"sound/vo/oasis/allies/hq_paksouthdyn.wav",
	"sound/vo/oasis/allies/hq_pumpdis.wav",
	"sound/vo/oasis/allies/hq_pumprep.wav",
	"sound/vo/oasis/allies/hq_pumprepd.wav",
	"sound/vo/oasis/allies/hq_pumpscon.wav",
	"sound/vo/oasis/allies/hq_pumpsrep.wav",
	"sound/vo/oasis/allies/hq_walldest.wav",
	"sound/vo/oasis/allies/hq_walldyn.wav",
	"sound/vo/oasis/axis/hq_cavesdrain.wav",
	"sound/vo/oasis/axis/hq_cavesflood.wav",
	"sound/vo/oasis/axis/hq_citydef.wav",
	"sound/vo/oasis/axis/hq_citylost.wav",
	"sound/vo/oasis/axis/hq_cityrecl.wav",
	"sound/vo/oasis/axis/hq_paknorthdef.wav",
	"sound/vo/oasis/axis/hq_paknorthdest.wav",
	"sound/vo/oasis/axis/hq_paksdef.wav",
	"sound/vo/oasis/axis/hq_paksouthdef.wav",
	"sound/vo/oasis/axis/hq_paksouthdest.wav",
	"sound/vo/oasis/axis/hq_pumpdis.wav",
	"sound/vo/oasis/axis/hq_pumprep.wav",
	"sound/vo/oasis/axis/hq_pumpsstop.wav",
	"sound/vo/oasis/axis/hq_pumpstop.wav",
	"sound/vo/oasis/axis/hq_walldef.wav",
	"sound/vo/oasis/axis/hq_walldest.wav",
	"sound/vo/oasis/news_oasis.wav",
	"sound/vo/radar/allies/hq_bunkercap.wav",
	"sound/vo/radar/allies/hq_bunkercapd.wav",
	"sound/vo/radar/allies/hq_bunkerrecl.wav",
	"sound/vo/radar/allies/hq_entrance1dest.wav",
	"sound/vo/radar/allies/hq_entrance1dyn.wav",
	"sound/vo/radar/allies/hq_entrance2dest.wav",
	"sound/vo/radar/allies/hq_entrance2dyn.wav",
	"sound/vo/radar/allies/hq_entrancesdyn.wav",
	"sound/vo/radar/allies/hq_radarelost.wav",
	"sound/vo/radar/allies/hq_radareret.wav",
	"sound/vo/radar/allies/hq_radaresec.wav",
	"sound/vo/radar/allies/hq_radaresteal.wav",
	"sound/vo/radar/allies/hq_radaretaken.wav",
	"sound/vo/radar/allies/hq_radarssteal.wav",
	"sound/vo/radar/allies/hq_radarwlost.wav",
	"sound/vo/radar/allies/hq_radarwret.wav",
	"sound/vo/radar/allies/hq_radarwsec.wav",
	"sound/vo/radar/allies/hq_radarwsteal.wav",
	"sound/vo/radar/allies/hq_radarwtaken.wav",
	"sound/vo/radar/axis/hq_bunkercapd.wav",
	"sound/vo/radar/axis/hq_bunkerrecl.wav",
	"sound/vo/radar/axis/hq_bunkerstop.wav",
	"sound/vo/radar/axis/hq_entrance1def.wav",
	"sound/vo/radar/axis/hq_entrance1dest.wav",
	"sound/vo/radar/axis/hq_entrance1stop.wav",
	"sound/vo/radar/axis/hq_entrance2def.wav",
	"sound/vo/radar/axis/hq_entrance2dest.wav",
	"sound/vo/radar/axis/hq_entrance2stop.wav",
	"sound/vo/radar/axis/hq_entrancesdef.wav",
	"sound/vo/radar/axis/hq_radaredef.wav",
	"sound/vo/radar/axis/hq_radarelost.wav",
	"sound/vo/radar/axis/hq_radareret.wav",
	"sound/vo/radar/axis/hq_radaresec.wav",
	"sound/vo/radar/axis/hq_radaretaken.wav",
	"sound/vo/radar/axis/hq_radarsdef.wav",
	"sound/vo/radar/axis/hq_radarwdef.wav",
	"sound/vo/radar/axis/hq_radarwlost.wav",
	"sound/vo/radar/axis/hq_radarwret.wav",
	"sound/vo/radar/axis/hq_radarwsec.wav",
	"sound/vo/radar/axis/hq_radarwtaken.wav",
	"sound/vo/radar/news_radar.wav",
	"sound/vo/railgun/allies/hq_depotcap.wav",
	"sound/vo/railgun/allies/hq_depotcapd.wav",
	"sound/vo/railgun/allies/hq_depotrecl.wav",
	"sound/vo/railgun/allies/hq_gunctrldest.wav",
	"sound/vo/railgun/allies/hq_gunctrldyn.wav",
	"sound/vo/railgun/allies/hq_gunctrlrep.wav",
	"sound/vo/railgun/allies/hq_gunfirestop.wav",
	"sound/vo/railgun/allies/hq_switchlower.wav",
	"sound/vo/railgun/allies/hq_switchlowered.wav",
	"sound/vo/railgun/allies/hq_switchraise.wav",
	"sound/vo/railgun/allies/hq_switchraised.wav",
	"sound/vo/railgun/allies/hq_tug1depot.wav",
	"sound/vo/railgun/allies/hq_tug1loaded.wav",
	"sound/vo/railgun/allies/hq_tug1north.wav",
	"sound/vo/railgun/allies/hq_tug2loaded.wav",
	"sound/vo/railgun/allies/hq_tug2railgun.wav",
	"sound/vo/railgun/axis/hq_depotcap.wav",
	"sound/vo/railgun/axis/hq_depotcapd.wav",
	"sound/vo/railgun/axis/hq_depotrecl.wav",
	"sound/vo/railgun/axis/hq_gunctrlcon.wav",
	"sound/vo/railgun/axis/hq_gunctrldef.wav",
	"sound/vo/railgun/axis/hq_gunctrldest.wav",
	"sound/vo/railgun/axis/hq_gunfire.wav",
	"sound/vo/railgun/axis/hq_gunloaded.wav",
	"sound/vo/railgun/axis/hq_switchlower.wav",
	"sound/vo/railgun/axis/hq_switchlowered.wav",
	"sound/vo/railgun/axis/hq_switchraise.wav",
	"sound/vo/railgun/axis/hq_switchraised.wav",
	"sound/vo/railgun/axis/hq_tug1allies.wav",
	"sound/vo/railgun/axis/hq_tug1depot.wav",
	"sound/vo/railgun/axis/hq_tug1loaded.wav",
	"sound/vo/railgun/axis/hq_tug1north.wav",
	"sound/vo/railgun/axis/hq_tug2allies.wav",
	"sound/vo/railgun/axis/hq_tug2loaded.wav",
	"sound/vo/railgun/axis/hq_tug2railgun.wav",
	"sound/vo/railgun/news_railgun.wav",
	"sound/weapons/airstrike/airstrike_expl_1.wav",
	"sound/weapons/airstrike/airstrike_expl_2.wav",
	"sound/weapons/airstrike/airstrike_expl_3.wav",
	"sound/weapons/airstrike/airstrike_expl_far.wav",
	"sound/weapons/airstrike/airstrike_plane.wav",
	"sound/weapons/artillery/artillery_expl_1.wav",
	"sound/weapons/artillery/artillery_expl_2.wav",
	"sound/weapons/artillery/artillery_expl_3.wav",
	"sound/weapons/artillery/artillery_expl_far.wav",
	"sound/weapons/artillery/artillery_fly_1.wav",
	"sound/weapons/artillery/artillery_fly_2.wav",
	"sound/weapons/artillery/artillery_fly_3.wav",
	"sound/weapons/browning/browning_far.wav",
	"sound/weapons/browning/browning_fire.wav",
	"sound/weapons/browning/browning_heat.wav",
	"sound/weapons/colt/colt_far.wav",
	"sound/weapons/colt/colt_fire.wav",
	"sound/weapons/colt/colt_reload.wav",
	"sound/weapons/colt/colt_reload_akimbo.wav",
	"sound/weapons/colt/colt_reload_fast.wav",
	"sound/weapons/colt/colt_silence.wav",
	"sound/weapons/dynamite/dynamite_bounce.wav",
	"sound/weapons/dynamite/dynamite_expl.wav",
	"sound/weapons/dynamite/dynamite_expl_far.wav",
	"sound/weapons/dynamite/dynamite_timer.wav",
	"sound/weapons/fg42/fg42_far.wav",
	"sound/weapons/fg42/fg42_fire.wav",
	"sound/weapons/fg42/fg42_reload.wav",
	"sound/weapons/fg42/fg42_reload_fast.wav",
	"sound/weapons/flamethrower/flame_burn.wav",
	"sound/weapons/flamethrower/flame_fire.wav",
	"sound/weapons/flamethrower/flame_pilot.wav",
	"sound/weapons/flamethrower/flame_up.wav",
	"sound/weapons/garand/m1_far.wav",
	"sound/weapons/garand/m1_fire.wav",
	"sound/weapons/garand/m1_fire_grenade.wav",
	"sound/weapons/garand/m1_fire_last.wav",
	"sound/weapons/garand/m1_fire_silence.wav",
	"sound/weapons/garand/m1_fire_silence_last.wav",
	"sound/weapons/garand/m1_grenade_fly.wav",
	"sound/weapons/garand/m1_grenade_off.wav",
	"sound/weapons/garand/m1_grenade_on.wav",
	"sound/weapons/garand/m1_reload.wav",
	"sound/weapons/garand/m1_reload_grenade.wav",
	"sound/weapons/grenade/bounce_hard1.wav",
	"sound/weapons/grenade/bounce_hard2.wav",
	"sound/weapons/grenade/bounce_metal1.wav",
	"sound/weapons/grenade/bounce_metal2.wav",
	"sound/weapons/grenade/bounce_soft1.wav",
	"sound/weapons/grenade/bounce_soft2.wav",
	"sound/weapons/grenade/bounce_wood1.wav",
	"sound/weapons/grenade/bounce_wood2.wav",
	"sound/weapons/grenade/gren_expl.wav",
	"sound/weapons/grenade/gren_expl_far.wav",
	"sound/weapons/grenade/gren_expl_water.wav",
	"sound/weapons/grenade/gren_smoke.wav",
	"sound/weapons/grenade/gren_throw.wav",
	"sound/weapons/grenade/gren_timer1.wav",
	"sound/weapons/grenade/gren_timer2.wav",
	"sound/weapons/grenade/gren_timer3.wav",
	"sound/weapons/grenade/gren_timer4.wav",
	"sound/weapons/impact/flesh1.wav",
	"sound/weapons/impact/flesh2.wav",
	"sound/weapons/impact/flesh3.wav",
	"sound/weapons/impact/flesh4.wav",
	"sound/weapons/impact/flesh5.wav",
	"sound/weapons/impact/glass1.wav",
	"sound/weapons/impact/glass2.wav",
	"sound/weapons/impact/glass3.wav",
	"sound/weapons/impact/glass4.wav",
	"sound/weapons/impact/glass5.wav",
	"sound/weapons/impact/metal1.wav",
	"sound/weapons/impact/metal2.wav",
	"sound/weapons/impact/metal3.wav",
	"sound/weapons/impact/metal4.wav",
	"sound/weapons/impact/metal5.wav",
	"sound/weapons/impact/stone1.wav",
	"sound/weapons/impact/stone2.wav",
	"sound/weapons/impact/stone3.wav",
	"sound/weapons/impact/stone4.wav",
	"sound/weapons/impact/stone5.wav",
	"sound/weapons/impact/water1.wav",
	"sound/weapons/impact/water2.wav",
	"sound/weapons/impact/water3.wav",
	"sound/weapons/impact/water4.wav",
	"sound/weapons/impact/water5.wav",
	"sound/weapons/impact/wood1.wav",
	"sound/weapons/impact/wood2.wav",
	"sound/weapons/impact/wood3.wav",
	"sound/weapons/impact/wood4.wav",
	"sound/weapons/impact/wood5.wav",
	"sound/weapons/k43/k43_far.wav",
	"sound/weapons/k43/k43_fire.wav",
	"sound/weapons/k43/k43_fire_grenade.wav",
	"sound/weapons/k43/k43_fire_silence.wav",
	"sound/weapons/k43/k43_grenade_fly.wav",
	"sound/weapons/k43/k43_grenade_off.wav",
	"sound/weapons/k43/k43_grenade_on.wav",
	"sound/weapons/k43/k43_reload.wav",
	"sound/weapons/k43/k43_reload_grenade.wav",
	"sound/weapons/knife/knife_hit1.wav",
	"sound/weapons/knife/knife_hit2.wav",
	"sound/weapons/knife/knife_hit3.wav",
	"sound/weapons/knife/knife_hit4.wav",
	"sound/weapons/knife/knife_hitwall1.wav",
	"sound/weapons/knife/knife_slash1.wav",
	"sound/weapons/knife/knife_slash2.wav",
	"sound/weapons/knife/knife_slash3.wav",
	"sound/weapons/landmine/mine_bounce.wav",
	"sound/weapons/landmine/mine_expl.wav",
	"sound/weapons/landmine/mine_expl_far.wav",
	"sound/weapons/landmine/mine_on.wav",
	"sound/weapons/luger/luger_far.wav",
	"sound/weapons/luger/luger_fire.wav",
	"sound/weapons/luger/luger_reload.wav",
	"sound/weapons/luger/luger_reload_akimbo.wav",
	"sound/weapons/luger/luger_reload_fast.wav",
	"sound/weapons/luger/luger_silence.wav",
	"sound/weapons/mg42/mg42_far.wav",
	"sound/weapons/mg42/mg42_fire.wav",
	"sound/weapons/mg42/mg42_heat.wav",
	"sound/weapons/mg42/mg42_reload.wav",
	"sound/weapons/misc/change.wav",
	"sound/weapons/misc/fire_dry.wav",
	"sound/weapons/misc/fire_water.wav",
	"sound/weapons/misc/shell_metal1.wav",
	"sound/weapons/misc/shell_metal2.wav",
	"sound/weapons/misc/shell_metal3.wav",
	"sound/weapons/misc/shell_soft1.wav",
	"sound/weapons/misc/shell_soft2.wav",
	"sound/weapons/misc/shell_soft3.wav",
	"sound/weapons/misc/shell_stone1.wav",
	"sound/weapons/misc/shell_stone2.wav",
	"sound/weapons/misc/shell_stone3.wav",
	"sound/weapons/misc/shell_wood1.wav",
	"sound/weapons/misc/shell_wood2.wav",
	"sound/weapons/misc/shell_wood3.wav",
	"sound/weapons/misc/silence_off.wav",
	"sound/weapons/misc/silence_on.wav",
	"sound/weapons/mortar/mortar_expl.wav",
	"sound/weapons/mortar/mortar_expl1.wav",
	"sound/weapons/mortar/mortar_expl2.wav",
	"sound/weapons/mortar/mortar_expl3.wav",
	"sound/weapons/mortar/mortar_expl_far.wav",
	"sound/weapons/mortar/mortar_fire.wav",
	"sound/weapons/mortar/mortar_fly.wav",
	"sound/weapons/mortar/mortar_off.wav",
	"sound/weapons/mortar/mortar_on.wav",
	"sound/weapons/mp40/mp40_far.wav",
	"sound/weapons/mp40/mp40_fire.wav",
	"sound/weapons/mp40/mp40_reload.wav",
	"sound/weapons/mp40/mp40_reload_fast.wav",
	"sound/weapons/rocket/rocket_charge.wav",
	"sound/weapons/rocket/rocket_expl.wav",
	"sound/weapons/rocket/rocket_expl_far.wav",
	"sound/weapons/rocket/rocket_fire.wav",
	"sound/weapons/rocket/rocket_fly.wav",
	"sound/weapons/satchel/remote_fire.wav",
	"sound/weapons/satchel/remote_hum.wav",
	"sound/weapons/satchel/satchel_bounce.wav",
	"sound/weapons/satchel/satchel_expl.wav",
	"sound/weapons/satchel/satchel_expl_far.wav",
	"sound/weapons/sten/sten_fire.wav",
	"sound/weapons/sten/sten_heat.wav",
	"sound/weapons/sten/sten_reload.wav",
	"sound/weapons/sten/sten_reload_fast.wav",
	"sound/weapons/thompson/thompson_far.wav",
	"sound/weapons/thompson/thompson_fire.wav",
	"sound/weapons/thompson/thompson_reload.wav",
	"sound/weapons/thompson/thompson_reload_fast.wav",
	"sound/world/alarm_01.wav",
	"sound/world/alarm_02.wav",
	"sound/world/beeper.wav",
	"sound/world/boardbreak.wav",
	"sound/world/bubbles.wav",
	"sound/world/build.wav",
	"sound/world/chaircreak.wav",
	"sound/world/crickets_01.wav",
	"sound/world/crickets_02.wav",
	"sound/world/debris.wav",
	"sound/world/debris1.wav",
	"sound/world/debris2.wav",
	"sound/world/debris3.wav",
	"sound/world/desert.wav",
	"sound/world/dog_01.wav",
	"sound/world/dog_02.wav",
	"sound/world/dripping_01.wav",
	"sound/world/dripping_02.wav",
	"sound/world/fan_fast.wav",
	"sound/world/fan_med.wav",
	"sound/world/fan_slow.wav",
	"sound/world/fire_01.wav",
	"sound/world/fire_02.wav",
	"sound/world/flag.wav",
	"sound/world/flap.wav",
	"sound/world/glassbreak1.wav",
	"sound/world/glassbreak2.wav",
	"sound/world/glassbreak3.wav",
	"sound/world/hum.wav",
	"sound/world/icecrack.wav",
	"sound/world/leaves.wav",
	"sound/world/lights.wav",
	"sound/world/machine_01.wav",
	"sound/world/machine_02.wav",
	"sound/world/machine_03.wav",
	"sound/world/metalbreak.wav",
	"sound/world/owl.wav",
	"sound/world/parrot.wav",
	"sound/world/pigeon.wav",
	"sound/world/radio_allies.wav",
	"sound/world/radio_axis.wav",
	"sound/world/radio_static_01.wav",
	"sound/world/radio_static_02.wav",
	"sound/world/rain_hard.wav",
	"sound/world/rain_indoor.wav",
	"sound/world/rain_soft.wav",
	"sound/world/rain_tent.wav",
	"sound/world/rain_trickle.wav",
	"sound/world/rooster.wav",
	"sound/world/steam_01.wav",
	"sound/world/steam_02.wav",
	"sound/world/steam_03.wav",
	"sound/world/thunder_01.wav",
	"sound/world/thunder_02.wav",
	"sound/world/thunder_03.wav",
	"sound/world/thunder_04.wav",
	"sound/world/thunder_05.wav",
	"sound/world/transformer.wav",
	"sound/world/war.wav",
	"sound/world/waterpump.wav",
	"sound/world/water_01.wav",
	"sound/world/water_02.wav",
	"sound/world/water_03.wav",
	"sound/world/wind_city.wav",
	"sound/world/wind_forest.wav",
	"sound/world/wind_hall.wav",
	"sound/world/wind_mountain.wav",
	"sound/world/wind_ocean.wav",
	
	NULL
};
